In [13]:
import numpy as np
array_np=np.array(range(1,21))
print(array_np)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [14]:
summ=np.sum(array_np)
meann= np.mean(array_np)
mediann =np.median(array_np)
sd=np.std(array_np)
print(f"sum {summ} mean {meann } median {mediann} sd {sd}")
indicess=np.where(array_np>10)
print(f"index in array whose value > 10 {indicess}")

sum 210 mean 10.5 median 10.5 sd 5.766281297335398
index in array whose value > 10 (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int64),)


In [15]:
matrix_np=np.arange(1,17).reshape(4,4)
print(matrix_np)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [16]:
matrix_np=np.arange(1,17).reshape(4,4)
print(matrix_np)
matrix_transpose_np=matrix_np.transpose()
print(matrix_transpose_np)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [17]:
matrix_np_row_sum=np.sum(matrix_np,axis=1)
matrix_np_col_sum=np.sum(matrix_np,axis=0)
print("row wise sum:",matrix_np_row_sum)
print("col wise sum:",matrix_np_col_sum)

row wise sum: [10 26 42 58]
col wise sum: [28 32 36 40]


In [24]:
import random
matrix_np_1=np.random.randint(1, 21, size=(3, 3))
matrix_np_2=np.random.randint(1,20, size=(3,3))
print(f"matrix 1: {matrix_np_1}, \n matrix 2: {matrix_np_2}")
matrix_np_sum=matrix_np_1+matrix_np_2
matrix_np_mul=matrix_np_1 * matrix_np_2
matrix_np_sub=matrix_np_1-matrix_np_2

print(f"element wise details:\n sum: {matrix_np_sum},\n multipication: {matrix_np_mul}, \nsubtraction: {matrix_np_sub}")


matrix 1: [[14 19  7]
 [ 2 14 19]
 [ 6 13 15]], 
 matrix 2: [[18 18 11]
 [ 3 12 15]
 [19  4  4]]
element wise details:
 sum: [[32 37 18]
 [ 5 26 34]
 [25 17 19]],
 multipication: [[252 342  77]
 [  6 168 285]
 [114  52  60]], 
subtraction: [[ -4   1  -4]
 [ -1   2   4]
 [-13   9  11]]


In [25]:
matrix_reshape=np.arange(1,13).reshape(3,4)
print(matrix_reshape)
matrix_reshape_row_col_sliced=matrix_reshape[0:2,2:4]
print(f"sliced matrix with the first two rows and last two columns: {matrix_reshape_row_col_sliced} ")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
sliced matrix with the first two rows and last two columns: [[3 4]
 [7 8]] 


In [26]:
# Step 1: Create a 1D array of size 12
arr_1d = np.arange(1, 13)  # [1, 2, ..., 12]

# Step 2: Reshape to 3x4
arr_2d = arr_1d.reshape(3, 4)

# Step 3: Slice first two rows and last two columns
sliced = arr_2d[0:2, 2:4]

# Display
print("Original 1D Array:\n", arr_1d)
print("\nReshaped 2D Array (3x4):\n", arr_2d)
print("\nSliced Array (first two rows, last two columns):\n", sliced)

Original 1D Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped 2D Array (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Sliced Array (first two rows, last two columns):
 [[3 4]
 [7 8]]
